"use strict";
/**
 * !! Do not edit this file directly! This is generated from contents of the web
 * !! repository. If you really need to change something, make the change in the
 * !! web repository and run `npm run fetch-web`.
 *
 * Utility functions for working with TypeScript enums.
 * TypeScript enums at runtime behave very similar objects, however *numeric* enums have an reverse mapping behaviour.
 * This enum produces TypeScript code that's functionally equivalent to the object below it:
 * ```ts
 * enum TSEnum {
 * 	Bar = 1,
 * 	Baz = 2
 * }
 *
 * const JSObject = {
 * 	'1': 'Bar',
 * 	'2': 'Baz',
 * 	Bar: 1,
 * 	Baz: 2,
 * }
 * ```
 * Note that the keys on JSObject have been stringified, as per all JS objects.
 *
 * For string enums they're effectively just objects, e.g.
 * ```ts
 * enum TSEnum {
 * 	Foo = 'foo',
 * 	Bar = 'bar'
 * }
 *
 * const JSObject {
 * 	Foo: 'foo',
 * 	Bar: 'bar'
 * }
 * ```
 *
 * For enums containing both strings and numbers, the numbers are reverse mapped, strings are not. Horrible!
 *
 * This property makes iterating over enums at runtime very annoying. Enums are sometimes twice the size you expect,
 * and iterating using Object.keys/values/entries will contain undesired cases.
 *
 * This library provides methods akin to Object.length, Object.keys, Object.values and Object.entries for enums.
 * Whilst you *can* use Object.keys etc. for string enums, I'd recommend using these functions explicitly.
 *
 * When perf doesn't matter, use the safe versions. Where perf does matter, use the fast methods, but note there's a
 * slight chance of breakage in future TypeScript versions/compilers, since they're exploiting specifics of the
 * TS => JS enum implementation (this has actually changed in the past). This is copied from the website repo where
 * these functions are unit-tested so should be okay, but TS versions could go out of sync or something.
 */
var Util;
(function (Util) {
    let Enum;
    (function (Enum) {
        /**
         * Get the number of entries in an enum.
         * @param enumObj - Enum-like Object
         * @return number - The number of entries in the enum
         */
        function length(enumObj) {
            return keys(enumObj).length;
        }
        Enum.length = length;
        /**
         * Faster version of `Enum.length` for numeric enums.
         * @param enumObj - Numeric enum-like Object
         * @return number - The number of entries in the enum
         */
        function fastLengthNumeric(enumObj) {
            // Typescript reverse mappings mean these have exactly twice as many keys
            // at runtime as a regular Object.
            return Object.keys(enumObj).length / 2;
        }
        Enum.fastLengthNumeric = fastLengthNumeric;
        /**
         * Faster version of `Enum.length` for string enums.
         * @param enumObj - String enum-like Object
         * @return number - The number of entries in the enum
         */
        function fastLengthString(enumObj) {
            return Object.keys(enumObj).length;
        }
        Enum.fastLengthString = fastLengthString;
        /**
         * Get the enum's keys, ignoring any reverse-mapped values.
         * @param enumObj - Enum-like Object
         * @return An array of the enum's keys
         */
        function keys(enumObj) {
            return getOwnEnumerableNonNumericKeys(enumObj);
        }
        Enum.keys = keys;
        /**
         * Faster version of `Enum.keys` for numeric enums.
         * @param enumObj - Enum-like Object
         * @return An array of the enum's keys
         */
        function fastKeysNumeric(enumObj) {
            const keys = Object.keys(enumObj);
            return keys.slice(keys.length / 2, keys.length);
        }
        Enum.fastKeysNumeric = fastKeysNumeric;
        /**
         * Faster version of `Enum.keys` for string enums.
         * @param enumObj - Enum-like Object
         * @return An array of the enum's keys
         */
        function fastKeysString(enumObj) {
            return Object.keys(enumObj);
        }
        Enum.fastKeysString = fastKeysString;
        /**
         * Get the enum's values.
         * NOTE: If there are duplicate values in the enum, then there will also
         * be duplicate values in the result.
         * @param enumObj - Enum-like Object
         * @return An array of the enum's values
         */
        function values(enumObj) {
            return keys(enumObj).map((key) => enumObj[key]);
        }
        Enum.values = values;
        /**
         * Faster version of `Enum.keys` for numeric enums.
         * @param enumObj - Enum-like Object
         * @return An array of the enum's keys
         */
        function fastValuesNumeric(enumObj) {
            const values = Object.values(enumObj);
            return values.slice(values.length / 2, values.length);
        }
        Enum.fastValuesNumeric = fastValuesNumeric;
        /**
         * Faster version of `Enum.keys` for string enums.
         * @param enumObj - Enum-like Object
         * @return An array of the enum's keys
         */
        function fastValuesString(enumObj) {
            return Object.values(enumObj);
        }
        Enum.fastValuesString = fastValuesString;
        /**
         * Get the enum's entries as [key, value] tuples.
         * @param enumObj - Enum-like Object
         * @return An array of the enum's values
         */
        function entries(enumObj) {
            return keys(enumObj).map((key) => [key, enumObj[key]]);
        }
        Enum.entries = entries;
        /**
         * Faster version of `Enum.keys` for numeric enums.
         * @param enumObj - Enum-like Object
         * @return An array of the enum's keys
         */
        function fastEntriesNumeric(enumObj) {
            const entries = Object.entries(enumObj);
            return entries.slice(entries.length / 2, entries.length);
        }
        Enum.fastEntriesNumeric = fastEntriesNumeric;
        /**
         * Faster version of `Enum.keys` for string enums.
         * @param enumObj - Enum-like Object
         * @return An array of the enum's keys
         */
        function fastEntriesString(enumObj) {
            return Object.entries(enumObj);
        }
        Enum.fastEntriesString = fastEntriesString;
        /**
         * Return true if the specified object key value is NOT a numeric key.
         * @param key - An object key.
         * @return true if the specified object key value is NOT a numeric key.
         */
        function isNonNumericKey(key) {
            return (key !== String(Number.parseFloat(key)) ||
                // If you do this you're a psycho, but okay, this would be a bug otherwise
                key === 'NaN');
        }
        /**
         * Get all own enumerable string (non-numeric) keys of an object.
         * The order of the result is guaranteed to be in the same order in which the
         * properties were added to the object, due to the specification of the
         * Object.getOwnPropertyNames method.
         * @param obj - An object.
         * @return A list of all the object's own enumerable string (non-numeric) keys.
         */
        function getOwnEnumerableNonNumericKeys(obj) {
            return Object.getOwnPropertyNames(obj).filter((key) => Object.prototype.propertyIsEnumerable.call(obj, key) && isNonNumericKey(key));
        }
    })(Enum = Util.Enum || (Util.Enum = {}));
})(Util || (Util = {}));
