"use strict";
/**
 * !! Do not edit this file directly! This is generated from contents of the web
 * !! repository. If you really need to change something, make the change in the
 * !! web repository and run `npm run fetch-web`.
 *
 * Collection of constant values and types shared between the
 * https://github.com/momentum-mod/website monorepo and Panorama, containing:
 * - Types: TypeScript types and interfaces, primarily for modeling the DTOs
 *   (data transfer objects) returned by the backend.
 *   The C++ equivalents of these live in mom_api_models.h.
 * 	 See https://staging-api.momentum-mod.org/docs Schemas section, for
 * 	 detailed descriptions of every model/DTO.
 * - Enums: TypeScript enums for everything the backend uses.
 *   The C++ equivalents of these live in mom_api_shareddefs.h.
 * - Maps: Readonly KV maps, usually associating enum values with extra data,
 *   e.g. gamemodes to their names, prefixes, icons etc...
 *   We use Maps instead of Objects since JavaScript object keys can only be
 *   strings or symbols, and most of our enum values are numbers.
 *
 * These are fetched from https://github.com/momentum-mod/website/tree/main/libs/constants
 * to maintain a single source of truth across our TypeScript projects. Things
 * unique to Panorama don't need to live here; they can be defined in other
 * files in this codebase.
 */
var Web;
(function (Web) {
    Web.STEAM_APPIDS = [669270, 1802710];
    function approvedBspPath(key) {
        return `maps/${key}.bsp`;
    }
    Web.approvedBspPath = approvedBspPath;
    function approvedVmfsPath(key) {
        return `maps/${key}_VMFs.zip`;
    }
    Web.approvedVmfsPath = approvedVmfsPath;
    function submissionBspPath(key) {
        return `submissions/${key}.bsp`;
    }
    Web.submissionBspPath = submissionBspPath;
    function submissionVmfsPath(key) {
        return `submissions/${key}_VMFs.zip`;
    }
    Web.submissionVmfsPath = submissionVmfsPath;
    function imgSmallPath(key) {
        return `img/${key}-small.jpg`;
    }
    Web.imgSmallPath = imgSmallPath;
    function imgMediumPath(key) {
        return `img/${key}-medium.jpg`;
    }
    Web.imgMediumPath = imgMediumPath;
    function imgLargePath(key) {
        return `img/${key}-large.jpg`;
    }
    Web.imgLargePath = imgLargePath;
    function imgXlPath(key) {
        return `img/${key}-xl.jpg`;
    }
    Web.imgXlPath = imgXlPath;
    function runPath(key) {
        return `runs/${key}`;
    }
    Web.runPath = runPath;
    function mapListPath(type, version) {
        return `maplist/${type === FlatMapList.APPROVED ? 'approved' : 'submissions'}/${version}.dat`;
    }
    Web.mapListPath = mapListPath;
    function mapListDir(type) {
        return type === FlatMapList.APPROVED ? 'maplist/approved/' : 'maplist/submissions/';
    }
    Web.mapListDir = mapListDir;
    function mapReviewAssetPath(key) {
        return `mapreview/${key}`;
    }
    Web.mapReviewAssetPath = mapReviewAssetPath;
    Web.JWT_WEB_EXPIRY_TIME = '15m';
    Web.JWT_GAME_EXPIRY_TIME = '24h';
    Web.JWT_REFRESH_EXPIRY_TIME = '5d';
    Web.MAX_DAILY_REPORTS = 5;
    Web.MAX_MAP_IMAGES = 5;
    Web.MAX_BSP_SIZE = 300_000_000;
    Web.MAX_VMF_SIZE = 100_000_000;
    Web.MAX_MAP_IMAGE_SIZE = 10_000_000;
    Web.MAP_IMAGE_WIDTH = 2560;
    Web.MAP_IMAGE_HEIGHT = 1440;
    Web.MAX_CREDIT_DESCRIPTION_LENGTH = 64;
    Web.MAX_CHANGELOG_LENGTH = 1500;
    Web.MAX_REVIEW_LENGTH = 5000;
    Web.MAX_REVIEW_IMAGES = 20;
    Web.MAX_REVIEW_COMMENT_LENGTH = 1000;
    Web.MAX_TEST_INVITES = 20;
    Web.MIN_PUBLIC_TESTING_DURATION = 7 * 24 * 60 * 60 * 1000;
    Web.MAX_CREDITS_EXCEPT_TESTERS = 20;
    Web.MAX_BIO_LENGTH = 2000;
    Web.MIN_MAP_DESCRIPTION_LENGTH = 30; // Fuck you, make an effort
    Web.MAX_MAP_DESCRIPTION_LENGTH = 1500;
    Web.MIN_MAP_NAME_LENGTH = 3;
    Web.MAX_MAP_NAME_LENGTH = 32; // Seems high but this is actually a constant in engine.
    Web.MAX_MAP_SUGGESTION_COMMENT_LENGTH = 500;
    Web.PRE_SIGNED_URL_EXPIRE_TIME = 5 * 60;
    // Very permissive regex for whenever exact criteria not avoilable online
    const defaultRegex = /^[\w-]{3,40}$/;
    Web.SocialsData = {
        Discord: {
            icon: 'discord',
            regex: /^[\w-]{2,32}$/,
            example: 'username',
            url: 'discordapp.com/users'
        },
        Twitch: {
            icon: 'twitch',
            regex: /^[\w-]{4,25}$/,
            example: 'username',
            url: 'twitch.tv'
        },
        YouTube: {
            icon: 'youtube',
            regex: /^@[\w-]{3,30}$/,
            example: '@username',
            url: 'youtube.com'
        },
        Github: {
            icon: 'github',
            regex: /^[\w-]{2,39}$/,
            example: 'username',
            url: 'github.com'
        },
        Twitter: {
            icon: 'twitter',
            regex: /^[\w-]{2,15}$/,
            example: 'username',
            url: 'twitter.com'
        },
        Mastodon: {
            icon: 'mastodon',
            regex: /^(?:@[\w-]+){2}\.[\w-]+$/,
            example: '@user@instance',
            // For any Mastodon instance `foo`, user `user`, user's instance `instance`,
            // https://foo/@user@instance redirects to https://instance/@user.
            // So just using the official instance works for everything.
            url: 'mastodon.social'
        },
        LinkedIn: {
            icon: 'linkedin',
            regex: defaultRegex,
            example: 'firstname-lastname-12345',
            url: 'linkedin.com/in'
        },
        Instagram: {
            icon: 'instagram',
            regex: defaultRegex, // Sequential underscores are allowed
            example: 'username',
            url: 'instagram.com'
        },
        Spotify: {
            icon: 'spotify',
            regex: defaultRegex, // Just randomly generated alphanumeric
            example: '21ahtj33ps3kiiet4sqq4pnra',
            url: 'open.spotify.com/user'
        },
        Patreon: {
            icon: 'patreon',
            regex: defaultRegex,
            example: 'username',
            url: 'patreon.com'
        },
        'Ko-fi': {
            icon: 'kofi',
            regex: defaultRegex,
            example: 'username',
            url: 'ko-fi.com'
        },
        Paypal: {
            icon: 'paypal',
            // Either email or @whatever
            regex: /^@[\w-]{3,30}$/,
            example: 'username (Must be a paypal.me profile)',
            url: 'paypal.me'
        }
    };
    // This is the specific key Steam uses for all missing avatars.
    // They even kept it when migrating to Cloudflare!
    Web.STEAM_MISSING_AVATAR = 'fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb';
    Web.STEAM_MISSING_AVATAR_URL = `https://avatars.cloudflare.steamstatic.com/${Web.STEAM_MISSING_AVATAR}_full.jpg`;
    let ActivityType;
    (function (ActivityType) {
        ActivityType[ActivityType["ALL"] = 0] = "ALL";
        ActivityType[ActivityType["MAP_UPLOADED"] = 1] = "MAP_UPLOADED";
        ActivityType[ActivityType["MAP_APPROVED"] = 2] = "MAP_APPROVED";
        ActivityType[ActivityType["REVIEW_MADE"] = 3] = "REVIEW_MADE";
        ActivityType[ActivityType["PB_ACHIEVED"] = 4] = "PB_ACHIEVED";
        ActivityType[ActivityType["WR_ACHIEVED"] = 5] = "WR_ACHIEVED";
        ActivityType[ActivityType["REPORT_FILED"] = 6] = "REPORT_FILED";
        ActivityType[ActivityType["USER_JOINED"] = 7] = "USER_JOINED";
    })(ActivityType = Web.ActivityType || (Web.ActivityType = {}));
    let AdminActivityType;
    (function (AdminActivityType) {
        AdminActivityType[AdminActivityType["USER_UPDATE"] = 0] = "USER_UPDATE";
        AdminActivityType[AdminActivityType["USER_CREATE_PLACEHOLDER"] = 1] = "USER_CREATE_PLACEHOLDER";
        AdminActivityType[AdminActivityType["USER_MERGE"] = 2] = "USER_MERGE";
        AdminActivityType[AdminActivityType["USER_DELETE"] = 3] = "USER_DELETE";
        AdminActivityType[AdminActivityType["MAP_UPDATE"] = 4] = "MAP_UPDATE";
        AdminActivityType[AdminActivityType["MAP_CONTENT_DELETE"] = 5] = "MAP_CONTENT_DELETE";
        AdminActivityType[AdminActivityType["REPORT_UPDATE"] = 6] = "REPORT_UPDATE";
        AdminActivityType[AdminActivityType["REPORT_RESOLVE"] = 7] = "REPORT_RESOLVE";
        AdminActivityType[AdminActivityType["REVIEW_DELETED"] = 8] = "REVIEW_DELETED";
        AdminActivityType[AdminActivityType["REVIEW_COMMENT_DELETED"] = 9] = "REVIEW_COMMENT_DELETED";
    })(AdminActivityType = Web.AdminActivityType || (Web.AdminActivityType = {}));
    let Ban;
    (function (Ban) {
        Ban[Ban["LEADERBOARDS"] = 1] = "LEADERBOARDS";
        Ban[Ban["ALIAS"] = 2] = "ALIAS";
        Ban[Ban["AVATAR"] = 4] = "AVATAR";
        Ban[Ban["BIO"] = 8] = "BIO";
        Ban[Ban["MAP_SUBMISSION"] = 16] = "MAP_SUBMISSION";
    })(Ban = Web.Ban || (Web.Ban = {}));
    // All valid (officially assigned) ISO 3166-1 Alpha-2 codes, scraped from Wikipedia
    let ISOCountryCode;
    (function (ISOCountryCode) {
        ISOCountryCode["AD"] = "Andorra";
        ISOCountryCode["AE"] = "United Arab Emirates";
        ISOCountryCode["AF"] = "Afghanistan";
        ISOCountryCode["AG"] = "Antigua and Barbuda";
        ISOCountryCode["AI"] = "Anguilla";
        ISOCountryCode["AL"] = "Albania";
        ISOCountryCode["AM"] = "Armenia";
        ISOCountryCode["AO"] = "Angola";
        ISOCountryCode["AQ"] = "Antarctica";
        ISOCountryCode["AR"] = "Argentina";
        ISOCountryCode["AS"] = "American Samoa";
        ISOCountryCode["AT"] = "Austria";
        ISOCountryCode["AU"] = "Australia";
        ISOCountryCode["AW"] = "Aruba";
        ISOCountryCode["AX"] = "\u00C5land Islands";
        ISOCountryCode["AZ"] = "Azerbaijan";
        ISOCountryCode["BA"] = "Bosnia and Herzegovina";
        ISOCountryCode["BB"] = "Barbados";
        ISOCountryCode["BD"] = "Bangladesh";
        ISOCountryCode["BE"] = "Belgium";
        ISOCountryCode["BF"] = "Burkina Faso";
        ISOCountryCode["BG"] = "Bulgaria";
        ISOCountryCode["BH"] = "Bahrain";
        ISOCountryCode["BI"] = "Burundi";
        ISOCountryCode["BJ"] = "Benin";
        ISOCountryCode["BL"] = "Saint Barth\u00E9lemy";
        ISOCountryCode["BM"] = "Bermuda";
        ISOCountryCode["BN"] = "Brunei Darussalam";
        ISOCountryCode["BO"] = "Bolivia";
        ISOCountryCode["BQ"] = "Bonaire";
        ISOCountryCode["BR"] = "Brazil";
        ISOCountryCode["BS"] = "Bahamas";
        ISOCountryCode["BT"] = "Bhutan";
        ISOCountryCode["BV"] = "Bouvet Island";
        ISOCountryCode["BW"] = "Botswana";
        ISOCountryCode["BY"] = "Belarus";
        ISOCountryCode["BZ"] = "Belize";
        ISOCountryCode["CA"] = "Canada";
        ISOCountryCode["CC"] = "Cocos (Keeling) Islands";
        ISOCountryCode["CD"] = "Congo";
        ISOCountryCode["CF"] = "Central African Republic";
        // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
        ISOCountryCode["CG"] = "Congo";
        ISOCountryCode["CH"] = "Switzerland";
        ISOCountryCode["CI"] = "Ivory Coast";
        ISOCountryCode["CK"] = "Cook Islands";
        ISOCountryCode["CL"] = "Chile";
        ISOCountryCode["CM"] = "Cameroon";
        ISOCountryCode["CN"] = "China";
        ISOCountryCode["CO"] = "Colombia";
        ISOCountryCode["CR"] = "Costa Rica";
        ISOCountryCode["CU"] = "Cuba";
        ISOCountryCode["CV"] = "Cabo Verde";
        ISOCountryCode["CW"] = "Curacao";
        ISOCountryCode["CX"] = "Christmas Island";
        ISOCountryCode["CY"] = "Cyprus";
        ISOCountryCode["CZ"] = "Czechia";
        ISOCountryCode["DE"] = "Germany";
        ISOCountryCode["DJ"] = "Djibouti";
        ISOCountryCode["DK"] = "Denmark";
        ISOCountryCode["DM"] = "Dominica";
        ISOCountryCode["DO"] = "Dominican Republic";
        ISOCountryCode["DZ"] = "Algeria";
        ISOCountryCode["EC"] = "Ecuador";
        ISOCountryCode["EE"] = "Estonia";
        ISOCountryCode["EG"] = "Egypt";
        ISOCountryCode["EH"] = "Western Sahara";
        ISOCountryCode["ER"] = "Eritrea";
        ISOCountryCode["ES"] = "Spain";
        ISOCountryCode["ET"] = "Ethiopia";
        ISOCountryCode["FI"] = "Finland";
        ISOCountryCode["FJ"] = "Fiji";
        ISOCountryCode["FK"] = "Falkland Islands (Malvinas)";
        ISOCountryCode["FM"] = "Federated States of Micronesia";
        ISOCountryCode["FO"] = "Faroe Islands";
        ISOCountryCode["FR"] = "France";
        ISOCountryCode["GA"] = "Gabon";
        ISOCountryCode["GB"] = "United Kingdom";
        ISOCountryCode["GD"] = "Grenada";
        ISOCountryCode["GE"] = "Georgia";
        ISOCountryCode["GF"] = "French Guiana";
        ISOCountryCode["GG"] = "Guernsey";
        ISOCountryCode["GH"] = "Ghana";
        ISOCountryCode["GI"] = "Gibraltar";
        ISOCountryCode["GL"] = "Greenland";
        ISOCountryCode["GM"] = "Gambia";
        ISOCountryCode["GN"] = "Guinea";
        ISOCountryCode["GP"] = "Guadeloupe";
        ISOCountryCode["GQ"] = "Equatorial Guinea";
        ISOCountryCode["GR"] = "Greece";
        ISOCountryCode["GS"] = "South Georgia and the South Sandwich Islands";
        ISOCountryCode["GT"] = "Guatemala";
        ISOCountryCode["GU"] = "Guam";
        ISOCountryCode["GW"] = "Guinea-Bissau";
        ISOCountryCode["GY"] = "Guyana";
        ISOCountryCode["HK"] = "Hong Kong";
        ISOCountryCode["HM"] = "Heard Island and McDonald Islands";
        ISOCountryCode["HN"] = "Honduras";
        ISOCountryCode["HR"] = "Croatia";
        ISOCountryCode["HT"] = "Haiti";
        ISOCountryCode["HU"] = "Hungary";
        ISOCountryCode["ID"] = "Indonesia";
        ISOCountryCode["IE"] = "Ireland";
        ISOCountryCode["IL"] = "Israel";
        ISOCountryCode["IM"] = "Isle of Man";
        ISOCountryCode["IN"] = "India";
        ISOCountryCode["IO"] = "British Indian Ocean Territory";
        ISOCountryCode["IQ"] = "Iraq";
        ISOCountryCode["IR"] = "Islamic Republic of Iran";
        ISOCountryCode["IS"] = "Iceland";
        ISOCountryCode["IT"] = "Italy";
        ISOCountryCode["JE"] = "Jersey";
        ISOCountryCode["JM"] = "Jamaica";
        ISOCountryCode["JO"] = "Jordan";
        ISOCountryCode["JP"] = "Japan";
        ISOCountryCode["KE"] = "Kenya";
        ISOCountryCode["KG"] = "Kyrgyzstan";
        ISOCountryCode["KH"] = "Cambodia";
        ISOCountryCode["KI"] = "Kiribati";
        ISOCountryCode["KM"] = "Comoros";
        ISOCountryCode["KN"] = "Saint Kitts and Nevis";
        ISOCountryCode["KP"] = "Democratic People's Republic of Korea";
        ISOCountryCode["KR"] = "Korea";
        ISOCountryCode["KW"] = "Kuwait";
        ISOCountryCode["KY"] = "Cayman Islands";
        ISOCountryCode["KZ"] = "Kazakhstan";
        ISOCountryCode["LA"] = "Lao People's Democratic Republic";
        ISOCountryCode["LB"] = "Lebanon";
        ISOCountryCode["LC"] = "Saint Lucia";
        ISOCountryCode["LI"] = "Liechtenstein";
        ISOCountryCode["LK"] = "Sri Lanka";
        ISOCountryCode["LR"] = "Liberia";
        ISOCountryCode["LS"] = "Lesotho";
        ISOCountryCode["LT"] = "Lithuania";
        ISOCountryCode["LU"] = "Luxembourg";
        ISOCountryCode["LV"] = "Latvia";
        ISOCountryCode["LY"] = "Libya";
        ISOCountryCode["MA"] = "Morocco";
        ISOCountryCode["MC"] = "Monaco";
        ISOCountryCode["MD"] = "Moldova";
        ISOCountryCode["ME"] = "Montenegro";
        ISOCountryCode["MF"] = "Saint Martin";
        ISOCountryCode["MG"] = "Madagascar";
        ISOCountryCode["MH"] = "Marshall Islands";
        ISOCountryCode["MK"] = "North Macedonia";
        ISOCountryCode["ML"] = "Mali";
        ISOCountryCode["MM"] = "Myanmar";
        ISOCountryCode["MN"] = "Mongolia";
        ISOCountryCode["MO"] = "Macao";
        ISOCountryCode["MP"] = "Northern Mariana Islands";
        ISOCountryCode["MQ"] = "Martinique";
        ISOCountryCode["MR"] = "Mauritania";
        ISOCountryCode["MS"] = "Montserrat";
        ISOCountryCode["MT"] = "Malta";
        ISOCountryCode["MU"] = "Mauritius";
        ISOCountryCode["MV"] = "Maldives";
        ISOCountryCode["MW"] = "Malawi";
        ISOCountryCode["MX"] = "Mexico";
        ISOCountryCode["MY"] = "Malaysia";
        ISOCountryCode["MZ"] = "Mozambique";
        ISOCountryCode["NA"] = "Namibia";
        ISOCountryCode["NC"] = "New Caledonia";
        ISOCountryCode["NE"] = "Niger";
        ISOCountryCode["NF"] = "Norfolk Island";
        ISOCountryCode["NG"] = "Nigeria";
        ISOCountryCode["NI"] = "Nicaragua";
        ISOCountryCode["NL"] = "Netherlands";
        ISOCountryCode["NO"] = "Norway";
        ISOCountryCode["NP"] = "Nepal";
        ISOCountryCode["NR"] = "Nauru";
        ISOCountryCode["NU"] = "Niue";
        ISOCountryCode["NZ"] = "New Zealand";
        ISOCountryCode["OM"] = "Oman";
        ISOCountryCode["PA"] = "Panama";
        ISOCountryCode["PE"] = "Peru";
        ISOCountryCode["PF"] = "French Polynesia";
        ISOCountryCode["PG"] = "Papua New Guinea";
        ISOCountryCode["PH"] = "Philippines";
        ISOCountryCode["PK"] = "Pakistan";
        ISOCountryCode["PL"] = "Poland";
        ISOCountryCode["PM"] = "Saint Pierre and Miquelon";
        ISOCountryCode["PN"] = "Pitcairn";
        ISOCountryCode["PR"] = "Puerto Rico";
        ISOCountryCode["PS"] = "Palestine";
        ISOCountryCode["PT"] = "Portugal";
        ISOCountryCode["PW"] = "Palau";
        ISOCountryCode["PY"] = "Paraguay";
        ISOCountryCode["QA"] = "Qatar";
        ISOCountryCode["RE"] = "R\u00E9union";
        ISOCountryCode["RO"] = "Romania";
        ISOCountryCode["RS"] = "Serbia";
        ISOCountryCode["RU"] = "Russian Federation";
        ISOCountryCode["RW"] = "Rwanda";
        ISOCountryCode["SA"] = "Saudi Arabia";
        ISOCountryCode["SB"] = "Solomon Islands";
        ISOCountryCode["SC"] = "Seychelles";
        ISOCountryCode["SD"] = "Sudan";
        ISOCountryCode["SE"] = "Sweden";
        ISOCountryCode["SG"] = "Singapore";
        ISOCountryCode["SH"] = "Saint Helena";
        ISOCountryCode["SI"] = "Slovenia";
        ISOCountryCode["SJ"] = "Svalbard and Jan Mayen";
        ISOCountryCode["SK"] = "Slovakia";
        ISOCountryCode["SL"] = "Sierra Leone";
        ISOCountryCode["SM"] = "San Marino";
        ISOCountryCode["SN"] = "Senegal";
        ISOCountryCode["SO"] = "Somalia";
        ISOCountryCode["SR"] = "Suriname";
        ISOCountryCode["SS"] = "South Sudan";
        ISOCountryCode["ST"] = "Sao Tome and Principe";
        ISOCountryCode["SV"] = "El Salvador";
        ISOCountryCode["SX"] = "Sint Maarten";
        ISOCountryCode["SY"] = "Syrian Arab Republic";
        ISOCountryCode["SZ"] = "Eswatini";
        ISOCountryCode["TC"] = "Turks and Caicos Islands";
        ISOCountryCode["TD"] = "Chad";
        ISOCountryCode["TF"] = "French Southern Territories";
        ISOCountryCode["TG"] = "Togo";
        ISOCountryCode["TH"] = "Thailand";
        ISOCountryCode["TJ"] = "Tajikistan";
        ISOCountryCode["TK"] = "Tokelau";
        ISOCountryCode["TL"] = "Timor-Leste";
        ISOCountryCode["TM"] = "Turkmenistan";
        ISOCountryCode["TN"] = "Tunisia";
        ISOCountryCode["TO"] = "Tonga";
        ISOCountryCode["TR"] = "Turkey";
        ISOCountryCode["TT"] = "Trinidad and Tobago";
        ISOCountryCode["TV"] = "Tuvalu";
        ISOCountryCode["TW"] = "Taiwan";
        ISOCountryCode["TZ"] = "Tanzania";
        ISOCountryCode["UA"] = "Ukraine";
        ISOCountryCode["UG"] = "Uganda";
        ISOCountryCode["UM"] = "United States Minor Outlying Islands";
        ISOCountryCode["US"] = "United States of America";
        ISOCountryCode["UY"] = "Uruguay";
        ISOCountryCode["UZ"] = "Uzbekistan";
        ISOCountryCode["VA"] = "Holy See";
        ISOCountryCode["VC"] = "Saint Vincent and the Grenadines";
        ISOCountryCode["VE"] = "Venezuela";
        ISOCountryCode["VG"] = "British Virgin Islands";
        ISOCountryCode["VI"] = "U.S. Virgin Islands";
        ISOCountryCode["VN"] = "Viet Nam";
        ISOCountryCode["VU"] = "Vanuatu";
        ISOCountryCode["WF"] = "Wallis and Futuna";
        ISOCountryCode["WS"] = "Samoa";
        ISOCountryCode["YE"] = "Yemen";
        ISOCountryCode["YT"] = "Mayotte";
        ISOCountryCode["ZA"] = "South Africa";
        ISOCountryCode["ZM"] = "Zambia";
        ISOCountryCode["ZW"] = "Zimbabwe";
    })(ISOCountryCode = Web.ISOCountryCode || (Web.ISOCountryCode = {}));
    let FlatMapList;
    (function (FlatMapList) {
        FlatMapList["APPROVED"] = "approved";
        FlatMapList["SUBMISSION"] = "submission";
    })(FlatMapList = Web.FlatMapList || (Web.FlatMapList = {}));
    /**
     * All the modes available in Momentum.
     */
    let Gamemode;
    (function (Gamemode) {
        Gamemode[Gamemode["SURF"] = 1] = "SURF";
        Gamemode[Gamemode["BHOP"] = 2] = "BHOP";
        Gamemode[Gamemode["BHOP_HL1"] = 3] = "BHOP_HL1";
        Gamemode[Gamemode["CLIMB_MOM"] = 4] = "CLIMB_MOM";
        Gamemode[Gamemode["CLIMB_KZT"] = 5] = "CLIMB_KZT";
        Gamemode[Gamemode["CLIMB_16"] = 6] = "CLIMB_16";
        Gamemode[Gamemode["RJ"] = 7] = "RJ";
        Gamemode[Gamemode["SJ"] = 8] = "SJ";
        Gamemode[Gamemode["AHOP"] = 9] = "AHOP";
        Gamemode[Gamemode["CONC"] = 10] = "CONC";
        Gamemode[Gamemode["DEFRAG_CPM"] = 11] = "DEFRAG_CPM";
        Gamemode[Gamemode["DEFRAG_VQ3"] = 12] = "DEFRAG_VQ3";
        Gamemode[Gamemode["DEFRAG_VTG"] = 13] = "DEFRAG_VTG";
    })(Gamemode = Web.Gamemode || (Web.Gamemode = {}));
    /**
     * The outer categories that gamemodes are grouped into.
     */
    let GamemodeCategory;
    (function (GamemodeCategory) {
        GamemodeCategory[GamemodeCategory["SURF"] = 1] = "SURF";
        GamemodeCategory[GamemodeCategory["BHOP"] = 2] = "BHOP";
        GamemodeCategory[GamemodeCategory["CLIMB"] = 3] = "CLIMB";
        GamemodeCategory[GamemodeCategory["RJ"] = 4] = "RJ";
        GamemodeCategory[GamemodeCategory["SJ"] = 5] = "SJ";
        GamemodeCategory[GamemodeCategory["AHOP"] = 6] = "AHOP";
        GamemodeCategory[GamemodeCategory["CONC"] = 7] = "CONC";
        GamemodeCategory[GamemodeCategory["DEFRAG"] = 8] = "DEFRAG";
    })(GamemodeCategory = Web.GamemodeCategory || (Web.GamemodeCategory = {}));
    /**
     * All the image formats we support in different places.
     *
     * We could support more images if we really wanted, but WebP really isn't
     * that impressive vs mozjpeg jpegs, and we use mozjpeg to compress submitted
     * MapImage PNGs, so not much point bothering. Also fuck Google.
     */
    let ImageType;
    (function (ImageType) {
        ImageType[ImageType["JPG"] = 0] = "JPG";
        ImageType[ImageType["PNG"] = 1] = "PNG";
    })(ImageType = Web.ImageType || (Web.ImageType = {}));
    // Enum is string based to make using as object keys easier
    let KillswitchType;
    (function (KillswitchType) {
        KillswitchType["NEW_SIGNUPS"] = "NEW_SIGNUPS";
        KillswitchType["RUN_SUBMISSION"] = "RUN_SUBMISSION";
        KillswitchType["MAP_SUBMISSION"] = "MAP_SUBMISSION";
        KillswitchType["MAP_REVIEWS"] = "MAP_REVIEWS";
    })(KillswitchType = Web.KillswitchType || (Web.KillswitchType = {}));
    let LeaderboardType;
    (function (LeaderboardType) {
        LeaderboardType[LeaderboardType["RANKED"] = 0] = "RANKED";
        LeaderboardType[LeaderboardType["UNRANKED"] = 1] = "UNRANKED";
        LeaderboardType[LeaderboardType["HIDDEN"] = 2] = "HIDDEN";
        LeaderboardType[LeaderboardType["IN_SUBMISSION"] = 3] = "IN_SUBMISSION";
    })(LeaderboardType = Web.LeaderboardType || (Web.LeaderboardType = {}));
    let MapCreditType;
    (function (MapCreditType) {
        /* Contributed significant work to the map */
        MapCreditType[MapCreditType["AUTHOR"] = 0] = "AUTHOR";
        /* Did minor work on the map */
        MapCreditType[MapCreditType["CONTRIBUTOR"] = 1] = "CONTRIBUTOR";
        /* Tested the map during development, or submitted reviews during map
         * submission testing phases */
        MapCreditType[MapCreditType["TESTER"] = 2] = "TESTER";
        /* Any miscellaneous contributions, e.g. donations, encouragement etc. */
        MapCreditType[MapCreditType["SPECIAL_THANKS"] = 3] = "SPECIAL_THANKS";
    })(MapCreditType = Web.MapCreditType || (Web.MapCreditType = {}));
    let MapStatus;
    (function (MapStatus) {
        /* Completed submission and is available to everyone */
        MapStatus[MapStatus["APPROVED"] = 0] = "APPROVED";
        /* Available in the Beta tab to users with an accepted MapTestingInvite */
        MapStatus[MapStatus["PRIVATE_TESTING"] = 1] = "PRIVATE_TESTING";
        /* Awaiting approval from a REVIEWER before it can be made public */
        MapStatus[MapStatus["CONTENT_APPROVAL"] = 2] = "CONTENT_APPROVAL";
        /* Available to all users in the Beta tab*/
        MapStatus[MapStatus["PUBLIC_TESTING"] = 3] = "PUBLIC_TESTING";
        /* Awaiting final approval from a MODERATOR/ADMIN */
        MapStatus[MapStatus["FINAL_APPROVAL"] = 4] = "FINAL_APPROVAL";
        /* Anything that has been disabled for some reason, such as rejected map
  submissions, maps with critical bugs (that may often be fixed and re-enabled),
  maps with a DMCA claim, etc. */
        MapStatus[MapStatus["DISABLED"] = 5] = "DISABLED";
    })(MapStatus = Web.MapStatus || (Web.MapStatus = {}));
    Web.CombinedMapStatuses = Object.freeze({
        IN_SUBMISSION: [
            MapStatus.PRIVATE_TESTING,
            MapStatus.PUBLIC_TESTING,
            MapStatus.CONTENT_APPROVAL,
            MapStatus.FINAL_APPROVAL
        ]
    });
    let MapSubmissionType;
    (function (MapSubmissionType) {
        MapSubmissionType[MapSubmissionType["ORIGINAL"] = 0] = "ORIGINAL";
        MapSubmissionType[MapSubmissionType["PORT"] = 1] = "PORT";
        MapSubmissionType[MapSubmissionType["SPECIAL"] = 2] = "SPECIAL";
    })(MapSubmissionType = Web.MapSubmissionType || (Web.MapSubmissionType = {}));
    let MapTestInviteState;
    (function (MapTestInviteState) {
        MapTestInviteState[MapTestInviteState["UNREAD"] = 0] = "UNREAD";
        MapTestInviteState[MapTestInviteState["ACCEPTED"] = 1] = "ACCEPTED";
        MapTestInviteState[MapTestInviteState["DECLINED"] = 2] = "DECLINED";
    })(MapTestInviteState = Web.MapTestInviteState || (Web.MapTestInviteState = {}));
    let ReportCategory;
    (function (ReportCategory) {
        ReportCategory[ReportCategory["OTHER"] = 0] = "OTHER";
        ReportCategory[ReportCategory["INAPPROPRIATE_CONTENT"] = 1] = "INAPPROPRIATE_CONTENT";
        ReportCategory[ReportCategory["PLAGIARISM"] = 2] = "PLAGIARISM";
        ReportCategory[ReportCategory["SPAM"] = 3] = "SPAM";
    })(ReportCategory = Web.ReportCategory || (Web.ReportCategory = {}));
    let ReportType;
    (function (ReportType) {
        ReportType[ReportType["USER_PROFILE_REPORT"] = 0] = "USER_PROFILE_REPORT";
        ReportType[ReportType["MAP_REPORT"] = 1] = "MAP_REPORT";
        ReportType[ReportType["MAP_COMMENT_REPORT"] = 2] = "MAP_COMMENT_REPORT";
    })(ReportType = Web.ReportType || (Web.ReportType = {}));
    let Role;
    (function (Role) {
        Role[Role["ADMIN"] = 1] = "ADMIN";
        Role[Role["MODERATOR"] = 2] = "MODERATOR";
        Role[Role["VERIFIED"] = 4] = "VERIFIED";
        Role[Role["PLACEHOLDER"] = 8] = "PLACEHOLDER";
        Role[Role["DELETED"] = 16] = "DELETED";
        Role[Role["REVIEWER"] = 32] = "REVIEWER";
        Role[Role["MAPPER"] = 64] = "MAPPER";
        Role[Role["PORTER"] = 128] = "PORTER";
    })(Role = Web.Role || (Web.Role = {}));
    Web.CombinedRoles = Object.freeze({
        MOD_OR_ADMIN: Role.MODERATOR | Role.ADMIN,
        REVIEWER_AND_ABOVE: Role.REVIEWER | Role.MODERATOR | Role.ADMIN,
        MAPPER_OR_PORTER: Role.MAPPER | Role.PORTER,
        MAPPER_AND_ABOVE: Role.MAPPER | Role.PORTER | Role.REVIEWER | Role.MODERATOR | Role.ADMIN
    }); // These live in here as service logic and E2E need access.
    let RunValidationErrorType;
    (function (RunValidationErrorType) {
        RunValidationErrorType[RunValidationErrorType["BAD_TIMESTAMPS"] = 0] = "BAD_TIMESTAMPS";
        RunValidationErrorType[RunValidationErrorType["BAD_REPLAY_FILE"] = 1] = "BAD_REPLAY_FILE";
        RunValidationErrorType[RunValidationErrorType["BAD_META"] = 2] = "BAD_META";
        RunValidationErrorType[RunValidationErrorType["INVALID_STATS"] = 3] = "INVALID_STATS";
        RunValidationErrorType[RunValidationErrorType["OUT_OF_SYNC"] = 4] = "OUT_OF_SYNC";
        RunValidationErrorType[RunValidationErrorType["UNSUPPORTED_MODE"] = 5] = "UNSUPPORTED_MODE";
        RunValidationErrorType[RunValidationErrorType["FUCKY_BEHAVIOUR"] = 6] = "FUCKY_BEHAVIOUR";
        RunValidationErrorType[RunValidationErrorType["INTERNAL_ERROR"] = 7] = "INTERNAL_ERROR";
    })(RunValidationErrorType = Web.RunValidationErrorType || (Web.RunValidationErrorType = {}));
    Web.RunValidationErrors = {
        [RunValidationErrorType.BAD_TIMESTAMPS]: {
            code: 0,
            message: 'run timestamps were misordered'
        },
        [RunValidationErrorType.BAD_REPLAY_FILE]: {
            code: 1,
            message: 'invalid replay file'
        },
        [RunValidationErrorType.BAD_META]: { code: 2, message: 'invalid metadata' },
        [RunValidationErrorType.INVALID_STATS]: { code: 3, message: 'invalid stats' },
        [RunValidationErrorType.OUT_OF_SYNC]: {
            code: 4,
            message: 'replay data out of sync with submission times'
        },
        [RunValidationErrorType.UNSUPPORTED_MODE]: {
            code: 5,
            message: 'this mode is not currently supported'
        },
        [RunValidationErrorType.FUCKY_BEHAVIOUR]: {
            code: 6,
            message: 'unusual behaviour in replay'
        },
        [RunValidationErrorType.INTERNAL_ERROR]: {
            code: 7,
            message: 'an internal server error occurred'
        }
    };
    class RunValidationError extends Error {
        code;
        constructor(type) {
            super(Web.RunValidationErrors[type].message);
            this.code = Web.RunValidationErrors[type].code;
        }
    }
    Web.RunValidationError = RunValidationError;
    let Style;
    (function (Style) {
        Style[Style["NONE"] = 0] = "NONE";
        Style[Style["HSW"] = 1] = "HSW";
        Style[Style["SW"] = 2] = "SW";
        Style[Style["BW"] = 4] = "BW";
    })(Style = Web.Style || (Web.Style = {}));
    let TrackType;
    (function (TrackType) {
        TrackType[TrackType["MAIN"] = 0] = "MAIN";
        TrackType[TrackType["STAGE"] = 1] = "STAGE";
        TrackType[TrackType["BONUS"] = 2] = "BONUS";
    })(TrackType = Web.TrackType || (Web.TrackType = {}));
    Web.TrackTypeName = new Map([
        [TrackType.MAIN, 'Main'],
        [TrackType.STAGE, 'Stage'],
        [TrackType.BONUS, 'Bonus']
    ]);
    let ZoneType;
    (function (ZoneType) {
        ZoneType[ZoneType["ZONE_END"] = 0] = "ZONE_END";
        ZoneType[ZoneType["ZONE_START"] = 1] = "ZONE_START";
        ZoneType[ZoneType["ZONE_STAGE"] = 2] = "ZONE_STAGE";
        ZoneType[ZoneType["ZONE_CHECKPOINT"] = 3] = "ZONE_CHECKPOINT";
    })(ZoneType = Web.ZoneType || (Web.ZoneType = {}));
    Web.BanNames = new Map([
        [Ban.LEADERBOARDS, 'Leaderboards'],
        [Ban.ALIAS, 'Alias'],
        [Ban.AVATAR, 'Avatar'],
        [Ban.BIO, 'Bio'],
        [Ban.MAP_SUBMISSION, 'Map submission']
    ]);
    Web.GamemodeCategories = new Map([
        [GamemodeCategory.SURF, [Gamemode.SURF]],
        [GamemodeCategory.BHOP, [Gamemode.BHOP, Gamemode.BHOP_HL1]],
        [GamemodeCategory.RJ, [Gamemode.RJ]],
        [GamemodeCategory.SJ, [Gamemode.SJ]],
        [GamemodeCategory.AHOP, [Gamemode.AHOP]],
        [GamemodeCategory.CONC, [Gamemode.CONC]],
        [GamemodeCategory.DEFRAG, [Gamemode.DEFRAG_CPM, Gamemode.DEFRAG_VQ3, Gamemode.DEFRAG_VTG]],
        [GamemodeCategory.CLIMB, [Gamemode.CLIMB_KZT, Gamemode.CLIMB_MOM, Gamemode.CLIMB_16]]
    ]);
    Web.GamemodeInfo = new Map([
        [
            Gamemode.SURF,
            {
                category: GamemodeCategory.SURF,
                name: 'Surf',
                id: 'surf',
                prefix: 'surf',
                icon: 'surf'
            }
        ],
        [
            Gamemode.BHOP,
            {
                category: GamemodeCategory.BHOP,
                name: 'Bhop',
                id: 'bhop',
                prefix: 'bhop',
                icon: 'bhop'
            }
        ],
        [
            Gamemode.BHOP_HL1,
            {
                category: GamemodeCategory.BHOP,
                name: 'Bhop (HL1)',
                id: 'bhop_hl',
                prefix: 'bhophl',
                icon: 'bhop'
            }
        ],
        [
            Gamemode.CLIMB_MOM,
            {
                category: GamemodeCategory.CLIMB,
                name: 'Climb (Momentum)',
                id: 'kz_mom',
                prefix: 'kz',
                icon: 'climb'
            }
        ],
        [
            Gamemode.CLIMB_KZT,
            {
                category: GamemodeCategory.CLIMB,
                name: 'Climb (KZT)',
                id: 'kz_kzt',
                prefix: 'kzt',
                icon: 'climb'
            }
        ],
        [
            Gamemode.CLIMB_16,
            {
                category: GamemodeCategory.CLIMB,
                name: 'Climb (1.6)',
                id: 'kz_16',
                prefix: 'kz16',
                icon: 'climb'
            }
        ],
        [
            Gamemode.RJ,
            {
                category: GamemodeCategory.RJ,
                name: 'Rocket Jump',
                id: 'rj',
                prefix: 'rj',
                icon: 'rj'
            }
        ],
        [
            Gamemode.SJ,
            {
                category: GamemodeCategory.SJ,
                name: 'Sticky Jump',
                id: 'sj',
                prefix: 'sj',
                icon: 'sj'
            }
        ],
        [
            Gamemode.AHOP,
            {
                category: GamemodeCategory.AHOP,
                name: 'Ahop',
                id: 'ahop',
                prefix: 'ahop',
                icon: 'ahop'
            }
        ],
        [
            Gamemode.CONC,
            {
                category: GamemodeCategory.CONC,
                name: 'Conc',
                id: 'conc',
                prefix: 'conc',
                icon: 'conc'
            }
        ],
        [
            Gamemode.DEFRAG_CPM,
            {
                category: GamemodeCategory.DEFRAG,
                name: 'Defrag (CPM)',
                id: 'df_cpm',
                prefix: 'df',
                icon: 'defrag'
            }
        ],
        [
            Gamemode.DEFRAG_VQ3,
            {
                category: GamemodeCategory.DEFRAG,
                name: 'Defrag (VQ3)',
                id: 'df_vq3',
                prefix: 'df',
                icon: 'defrag'
            }
        ],
        [
            Gamemode.DEFRAG_VTG,
            {
                category: GamemodeCategory.DEFRAG,
                name: 'Defrag (Vintage)',
                id: 'df_vtg',
                prefix: 'df',
                icon: 'defrag'
            }
        ]
    ]);
    // Silly little system for passing whole categories into this structure, rather
    // than each individual gamemode, but structured so we could do single gamemodes
    // in future if needed. Lots of these are singleton categories but using them
    // for future-proofing, for example 100t surf would have the exact same rules
    // as regular surf.
    // JAVASCRIPT PLEASE ADD CONSTEXPR!!!
    const G = Gamemode; //
    const GC = GamemodeCategory;
    const Cats = (...gcs) => gcs.flatMap((gc) => Web.GamemodeCategories.get(gc));
    /**
     * A non-reflexive map of gamemodes and collections of gamemodes they can
     * *never* have compatibile leaderboards for.
     *
     * For example, there's *never* a possible case
     * where a surf leaderboard should also have a bhop leaderboard, that'd just be
     * jank 100-tick surf.
     *
     * Note the non-reflexivity, you might have a surf map that's worth a
     * leaderboard in ahop (e.g. utopia), but a ahop map would never have a surf
     * leaderboard, since that'd just be bhop with worse settings.
     */
    Web.IncompatibleGamemodes = new Map([
        [G.SURF, [Cats(GC.BHOP, GC.CLIMB)]],
        [G.BHOP, [Cats(GC.SURF, GC.CLIMB)]],
        [G.BHOP_HL1, [Cats(GC.SURF, GC.CLIMB)]],
        [G.CLIMB_MOM, [Cats(GC.SURF, GC.BHOP)]],
        [G.CLIMB_KZT, [Cats(GC.SURF, GC.BHOP)]],
        [G.CLIMB_16, [Cats(GC.SURF, GC.BHOP)]],
        [G.RJ, [Cats(GC.SURF, GC.CLIMB, GC.BHOP, GC.AHOP)]],
        [G.SJ, [Cats(GC.SURF, GC.CLIMB, GC.BHOP, GC.AHOP)]],
        [G.AHOP, [Cats(GC.SURF, GC.CLIMB)]],
        [G.CONC, [Cats(GC.SURF, GC.CLIMB, GC.BHOP, GC.AHOP)]],
        [G.DEFRAG_CPM, [Cats(GC.SURF, GC.CLIMB)]],
        [G.DEFRAG_VQ3, [Cats(GC.SURF, GC.CLIMB)]],
        [G.DEFRAG_VTG, [Cats(GC.SURF, GC.CLIMB)]]
    ].map(([k, v]) => [k, new Set(v.flat())]));
    Web.LeaderboardTypeName = new Map([
        [LeaderboardType.RANKED, 'Ranked'],
        [LeaderboardType.UNRANKED, 'Unranked'],
        [LeaderboardType.HIDDEN, 'Hidden']
    ]);
    Web.MapCreditNames = new Map([
        [MapCreditType.AUTHOR, 'Authors'],
        [MapCreditType.CONTRIBUTOR, 'Contributors'],
        [MapCreditType.TESTER, 'Testers'],
        [MapCreditType.SPECIAL_THANKS, 'Special Thanks']
    ]);
    /**
     * Stores what changes between map statuses are allowed by what users
     *
     * In table form:
     *
     * | From(Down), To(Across) | Approved | Private Testing | Content Approval | Public Testing | Final Approval | Disabled |
     * | ---------------------- | -------- | --------------- | ---------------- | -------------- | -------------- | -------- |
     * | Approved               |          |                 |                  |                |                | AM       |
     * | Private Testing        |          |                 | S                |                |                | AM       |
     * | Content Approval       |          | S               |                  | RAM            | AM             | AM       |
     * | Public Testing         |          |                 | AM               |                | S              | AM       |
     * | Final Approval         | AM       |                 |                  | S              |                | AM       |
     * | Disabled               | A†       | A               | A                | A              | A              |          |
     *
     * † Admins can only move from disabled to approved if the map has been approved once in the past
     */
    Web.MapStatusChangeRules = [
        { from: MapStatus.APPROVED, to: MapStatus.APPROVED, roles: [] },
        { from: MapStatus.APPROVED, to: MapStatus.PRIVATE_TESTING, roles: [] },
        { from: MapStatus.APPROVED, to: MapStatus.CONTENT_APPROVAL, roles: [] },
        { from: MapStatus.APPROVED, to: MapStatus.PUBLIC_TESTING, roles: [] },
        { from: MapStatus.APPROVED, to: MapStatus.FINAL_APPROVAL, roles: [] },
        { from: MapStatus.APPROVED, to: MapStatus.DISABLED, roles: [Role.ADMIN, Role.MODERATOR] },
        { from: MapStatus.PRIVATE_TESTING, to: MapStatus.APPROVED, roles: [] },
        { from: MapStatus.PRIVATE_TESTING, to: MapStatus.PRIVATE_TESTING, roles: [] },
        { from: MapStatus.PRIVATE_TESTING, to: MapStatus.CONTENT_APPROVAL, roles: ['submitter'] },
        { from: MapStatus.PRIVATE_TESTING, to: MapStatus.PUBLIC_TESTING, roles: [] },
        { from: MapStatus.PRIVATE_TESTING, to: MapStatus.FINAL_APPROVAL, roles: [] },
        { from: MapStatus.PRIVATE_TESTING, to: MapStatus.DISABLED, roles: [Role.ADMIN, Role.MODERATOR] },
        { from: MapStatus.CONTENT_APPROVAL, to: MapStatus.APPROVED, roles: [] },
        { from: MapStatus.CONTENT_APPROVAL, to: MapStatus.PRIVATE_TESTING, roles: ['submitter'] },
        { from: MapStatus.CONTENT_APPROVAL, to: MapStatus.CONTENT_APPROVAL, roles: [] },
        {
            from: MapStatus.CONTENT_APPROVAL,
            to: MapStatus.PUBLIC_TESTING,
            roles: [Role.REVIEWER, Role.ADMIN, Role.MODERATOR]
        },
        { from: MapStatus.CONTENT_APPROVAL, to: MapStatus.FINAL_APPROVAL, roles: [Role.ADMIN, Role.MODERATOR] },
        { from: MapStatus.CONTENT_APPROVAL, to: MapStatus.DISABLED, roles: [Role.ADMIN, Role.MODERATOR] },
        { from: MapStatus.PUBLIC_TESTING, to: MapStatus.APPROVED, roles: [] },
        { from: MapStatus.PUBLIC_TESTING, to: MapStatus.PRIVATE_TESTING, roles: [] },
        { from: MapStatus.PUBLIC_TESTING, to: MapStatus.CONTENT_APPROVAL, roles: [Role.ADMIN, Role.MODERATOR] },
        { from: MapStatus.PUBLIC_TESTING, to: MapStatus.PUBLIC_TESTING, roles: [] },
        { from: MapStatus.PUBLIC_TESTING, to: MapStatus.FINAL_APPROVAL, roles: ['submitter'] },
        { from: MapStatus.PUBLIC_TESTING, to: MapStatus.DISABLED, roles: [Role.ADMIN, Role.MODERATOR] },
        { from: MapStatus.FINAL_APPROVAL, to: MapStatus.APPROVED, roles: [Role.ADMIN, Role.MODERATOR] },
        { from: MapStatus.FINAL_APPROVAL, to: MapStatus.PRIVATE_TESTING, roles: [] },
        { from: MapStatus.FINAL_APPROVAL, to: MapStatus.CONTENT_APPROVAL, roles: [] },
        { from: MapStatus.FINAL_APPROVAL, to: MapStatus.PUBLIC_TESTING, roles: ['submitter'] },
        { from: MapStatus.FINAL_APPROVAL, to: MapStatus.FINAL_APPROVAL, roles: [] },
        { from: MapStatus.FINAL_APPROVAL, to: MapStatus.DISABLED, roles: [Role.ADMIN, Role.MODERATOR] },
        { from: MapStatus.DISABLED, to: MapStatus.APPROVED, roles: [Role.ADMIN] },
        { from: MapStatus.DISABLED, to: MapStatus.PRIVATE_TESTING, roles: [Role.ADMIN] },
        { from: MapStatus.DISABLED, to: MapStatus.CONTENT_APPROVAL, roles: [Role.ADMIN] },
        { from: MapStatus.DISABLED, to: MapStatus.PUBLIC_TESTING, roles: [Role.ADMIN] },
        { from: MapStatus.DISABLED, to: MapStatus.FINAL_APPROVAL, roles: [Role.ADMIN] },
        { from: MapStatus.DISABLED, to: MapStatus.DISABLED, roles: [] }
    ];
    Web.MapStatusName = new Map([
        [MapStatus.APPROVED, 'Approved'],
        [MapStatus.PRIVATE_TESTING, 'Private Testing'],
        [MapStatus.CONTENT_APPROVAL, 'Content Approval'],
        [MapStatus.PUBLIC_TESTING, 'Public Testing'],
        [MapStatus.FINAL_APPROVAL, 'Final Approval'],
        [MapStatus.DISABLED, 'Disabled']
    ]);
    Web.RoleNames = new Map([
        [Role.ADMIN, 'Admin'],
        [Role.MODERATOR, 'Moderator'],
        [Role.MAPPER, 'Mapper'],
        [Role.PORTER, 'Porter'],
        [Role.DELETED, 'Deleted'],
        [Role.PLACEHOLDER, 'Placeholder'],
        [Role.REVIEWER, 'Reviewer'],
        [Role.VERIFIED, 'Verified']
    ]);
    /**
     * The tickrates each gamemode uses. May change in future when we allow surf
     * 100 tick etc. 0.015 <=> 66
     * 0.01 <=> 100
     * 0.008 <=> 125
     * 0.0078125 <=> 128
     */
    Web.Tickrates = new Map([
        [Gamemode.AHOP, 0.015],
        [Gamemode.BHOP, 0.01],
        [Gamemode.BHOP_HL1, 0.004],
        [Gamemode.CLIMB_MOM, 0.01],
        [Gamemode.CLIMB_KZT, 0.01],
        [Gamemode.CLIMB_16, 0.01],
        [Gamemode.CONC, 0.01],
        [Gamemode.DEFRAG_CPM, 0.008],
        [Gamemode.DEFRAG_VQ3, 0.008],
        [Gamemode.DEFRAG_VTG, 0.008],
        [Gamemode.RJ, 0.015],
        [Gamemode.SJ, 0.015],
        [Gamemode.SURF, 0.015]
    ]);
    Web.ISO_8601_REGEXP = /[+-]?\d{4}(-[01]\d(-[0-3]\d(T[0-2]\d:[0-5]\d:?([0-5]\d(\.\d+)?)?[+-][0-2]\d:[0-5]\dZ?)?)?)?/;
    Web.MAP_NAME_REGEXP = /^[a-z][\d_a-z-]+$/;
    // Checks user alias for whitespace including braille whitespace which
    // javascript's regex engine doesn't include in \s.
    Web.NON_WHITESPACE_REGEXP = /^(?![\s\u2800]*$).+/;
    Web.YOUTUBE_ID_REGEXP = /^[\w-_]{11}$/;
    //#endregion
    let Order;
    (function (Order) {
        Order["ASC"] = "asc";
        Order["DESC"] = "desc";
    })(Order = Web.Order || (Web.Order = {}));
    let RunsGetAllOrder;
    (function (RunsGetAllOrder) {
        RunsGetAllOrder["DATE"] = "createdAt";
        RunsGetAllOrder["RUN_TIME"] = "time";
    })(RunsGetAllOrder = Web.RunsGetAllOrder || (Web.RunsGetAllOrder = {}));
})(Web || (Web = {}));
