#!/bin/bash
set -e

# Script to fetch constants from the website repo. Panorama/V8 doesn't
# understand import/export, so we strip them out and combine into one big
# namespace.

WEBSITE_REPO="https://github.com/momentum-mod/website"

if [[ $PWD == */panorama/tools ]]; then
  cd ../
fi

if [ ! -f package.json ] && [[ $PWD != */panorama ]]; then
  echo "Doesn't look like we're in the panorama directory, exiting"
  exit 1
fi

rm -rf ./constants-tmp
rm -rf ./website-tmp

if [ "$1" == "-b" ] || [ "$1" == "" ]; then
  echo "Fetching constants from website repo..."
  if [ "$1" == "-b" ]; then
   git clone -b "$2" $WEBSITE_REPO ./website-tmp 
  else
    git clone $WEBSITE_REPO ./website-tmp
  fi 
  
  mv ./website-tmp/libs/constants/src/ ./constants-tmp
  rm -rf ./website-tmp
elif [ "$1" == "-l" ]; then
  echo "Copying constants from local path"
  cp -r "$2"/libs/constants/src ./constants-tmp
elif [ "$1" == "-h" ]; then
  echo "usage: fetch-constants.sh [-b branch] [-l local-path] [-h]"
  exit 0
fi

cd ./constants-tmp || exit 1
rm index.ts types/models/prisma-correspondence.ts

echo "Generating constants.ts"
printf "/**
 * !! Do not edit this file directly! This is generated from contents of the web
 * !! repository. If you really need to change something, make the change in the
 * !! web repository and run \`npm run fetch-constants\`.
 *
 * Collection of constant values and types shared between the
 * https://github.com/momentum-mod/website monorepo and Panorama, containing:
 * - Types: TypeScript types and interfaces, primarily for modeling the DTOs
 *   (data transfer objects) returned by the backend.
 *   The C++ equivalents of these live in mom_api_models.h.
 * 	 See https://staging-api.momentum-mod.org/docs Schemas section, for
 * 	 detailed descriptions of every model/DTO.
 * - Enums: TypeScript enums for everything the backend uses.
 *   The C++ equivalents of these live in mom_api_shareddefs.h.
 * - Maps: Readonly KV maps, usually associating enum values with extra data,
 *   e.g. gamemodes to their names, prefixes, icons etc...
 *   We use Maps instead of Objects since JavaScript object keys can only be
 *   strings or symbols, and most of our enum values are numbers.
 *
 * These are fetched from https://github.com/momentum-mod/website/tree/main/libs/constants
 * to maintain a single source of truth across our TypeScript projects. Things
 * unique to Panorama don't need to live here; they can be defined in other
 * files in this codebase.
 */
namespace Constants {
 
  // Stub any broswer/node types we don't actually use:
  type File = never;
 
" > constants.ts

for file in **/*.ts **/*/*.ts; do
  sed -z 's/import[^;]*;\n*//g' "$file" |
  sed -zE 's/\/\/ *TODO[^\n]*\n//g' | 
  grep -vE '// ?prettier-ignore' >> constants.ts
  printf "\n" >> constants.ts
done

echo "}" >> constants.ts

echo "Running prettier"

npx prettier --write constants.ts
cd ../

echo "Moving constants.ts to scripts/common/"
mv ./constants-tmp/constants.ts ./scripts/constants.ts

echo "Cleaning up loose files"
rm -rf ./constants-tmp

echo "Creating Git commit"
git reset
git add ./scripts/constants.ts
#git commit -m 'chore: update website constants' --no-verify

echo "Done!"

